Fix Issues

diff --git a/wayweather b/wayweather
--- a/wayweather
+++ b/wayweather
@@ -6,8 +6,8 @@ if ! [[ -d "$LIBS_DIR" ]]; then
   LIBS_DIR="/usr/lib/wayweather"
 fi
 if ! [[ -d "$LIBS_DIR" ]]; then
-  echo "[ERROR] Libraries are missing, cannot continue"
-  echo "[INFO] Reinstall/Redownload wayweather"
+  echo -e "[\033[31mERROR\033[0m] Libraries are missing, cannot continue" >&2
+  echo -e "[\033[36mINFO\033\0m] Reinstall/Redownload wayweather" >&2
   exit 1
 fi
 
@@ -31,27 +31,7 @@ case $1 in
   show_help main
   ;;
 -v | --version)
-  for i in "$@"; do
-    case $i in
-    -h | --help)
-      show_help version
-      ;;
-    esac
-  done
-  echo "wayweather $(get_version)"
-  ;;
--g | --get)
-  for i in "$@"; do
-    case $i in
-    -h | --help)
-      show_help get
-      ;;
-    --no-icon)
-      NO_ICON=true
-      ;;
-    esac
-  done
-  waybar_return "$(if $NO_ICON; then echo "no-icon"; else echo ""; fi)"
+  waybar_return "$(if [[ -v NO_ICON ]]; then echo "no-icon"; else echo ""; fi)"
   ;;
 -s | --set)
   for i in "$@"; do
@@ -90,18 +70,18 @@ case $1 in
       fi
       write_conf set "lat=$LAT" "long=$LONG" "country=$COUNTRY" "city=$CITY" "$(if [[ "$UNITS" != "" ]]; then echo "units=$UNITS"; else echo ""; fi)"
     else
-      echo "[ERROR] Arguments Empty"
+      echo -e "[\033[31mERROR\033[0m] Arguments Empty" >&2
       exit 1
     fi
   elif [[ -v UNITS ]]; then
     if [[ "$UNITS" != "" ]]; then
       write_conf set "units=$UNITS"
     else
-      echo "[ERROR] Arguments Empty"
+      echo -e "[\033[31mERROR\033[0m] Arguments Empty" >&2
       exit 1
     fi
   else
-    echo "[ERROR] Missing Arguments"
+    echo -e "[\033[31mERROR\033[0m] Missing Arguments" >&2
     exit 1
   fi
   ;;
@@ -161,7 +141,7 @@ case $1 in
       ;;
     esac
   done
-  term_return "$(if $NO_ICON; then echo "no-icon"; else echo ""; fi)"
+  term_return "$(if [[ -v NO_ICON ]]; then echo "no-icon"; else echo ""; fi)"
   ;;
 -sd | --set-default)
   for i in "$@"; do
@@ -209,10 +189,10 @@ case $1 in
       ;;
     esac
   done
-  daemon "$(if $NO_ICON; then echo "no-icon"; else echo ""; fi)" "$(if [[ -v LOCATION ]]; then echo "location=$LOCATION"; else echo ""; fi)" "$(if [[ -v TIMER ]]; then echo "timer=$TIMER"; else echo ""; fi)"
+  daemon "$(if [[ -v NO_ICON ]]; then echo "no-icon"; else echo ""; fi)" "$(if [[ -v LOCATION ]]; then echo "location=$LOCATION"; else echo ""; fi)" "$(if [[ -v TIMER ]]; then echo "timer=$TIMER"; else echo ""; fi)"
   ;;
 *)
-  echo -e "[ERROR] Invalid Input, Showing Help Message\n"
+  echo -e "[\033[31mERROR\033[0m] Invalid Input, Showing Help Message\n" >&2
   show_help main
   ;;
 esac
