Add defaults

diff --git a/src/locations b/src/locations
--- a/src/locations
+++ b/src/locations
@@ -80,8 +80,31 @@ $(echo "$JSON" | jq ".[\"$INPUT\"].city"), $(echo "$JSON" | jq ".[\"$INPUT\"].co
 
 write_loc() {
   SAVE_PATH="$HOME/.config/wayweather/locations.json"
-  if $SAVE && [[ -v UNITS ]]; then
-    JSON="{\"$(cat "$SAVE_PATH" | jq length)\":{
+
+  for i in "$@"; do
+    case $i in
+    lat=*)
+      LAT="${i#*=}"
+      ;;
+    long=*)
+      LONG="${i#*=}"
+      ;;
+    country=*)
+      COUNTRY="${i#*=}"
+      ;;
+    city=*)
+      CITY="${i#*=}"
+      ;;
+    units=*)
+      UNITS="${i#*=}"
+      ;;
+    skip)
+      SKIP=true
+      ;;
+    esac
+  done
+
+  JSON="{\"$(cat "$SAVE_PATH" | jq length)\":{
 \"latitude\":$LAT,
 \"longitude\":$LONG,
 \"city\":\"$CITY\",
@@ -89,13 +112,53 @@ write_loc() {
 \"units\":\"$UNITS\",
 \"default\":false
 }}"
-    echo "[LOG] Saved location: $CITY, $COUNTRY ($LAT, $LONG) [$(if [[ "$UNITS" == "met" ]]; then echo "°C, mm, km/h"; else echo "°F, inch, mph"; fi)]"
-    # Add check for replacing with new confgigs
-    SAVE="$(cat "$SAVE_PATH" | jq ". += $(echo "$JSON" | jq -c)")"
-    echo "$SAVE" >"$SAVE_PATH"
+  echo "[LOG] Saved location: $CITY, $COUNTRY ($LAT, $LONG) [$(if [[ "$UNITS" == "met" ]]; then echo "°C, mm, km/h"; else echo "°F, inch, mph"; fi)]"
+  # Add check for replacing with new confgigs
+  SAVE="$(cat "$SAVE_PATH" | jq ". += $(echo "$JSON" | jq -c)")"
+  echo "$SAVE" >"$SAVE_PATH"
 
-    if [[ -v SKIP ]]; then
-      exit 1
+  if [[ -v SKIP ]]; then
+    exit 1
+  fi
+}
+
+default_loc() {
+  SAVE_PATH="$HOME/.config/wayweather/locations.json"
+  JSON="$(cat "$SAVE_PATH" | jq -c)"
+  DEFAULT=""
+
+  for index in $(seq 0 "$(($(echo "$JSON" | jq length) - 1))"); do
+    UNITS="$(if [[ $(echo "$JSON" | jq ".[\"$index\"].units") == '"met"' ]]; then echo "°C, mm, km/h"; else echo "°F, inch, mph"; fi)"
+    echo "[$index]\
+$(if [[ "$(echo "$JSON" | jq ".[\"$index\"].default")" == "true" ]]; then echo "*"; else echo ""; fi) \
+$(echo "$JSON" | jq ".[\"$index\"].city"), $(echo "$JSON" | jq ".[\"$index\"].country") \
+($(echo "$JSON" | jq ".[\"$index\"].latitude"), $(echo "$JSON" | jq ".[\"$index\"].longitude")) \
+[$UNITS]" | sed -e 's/"//g'
+    DEFAULT="$(if [[ "$(echo "$JSON" | jq ".[\"$index\"].default")" == "true" ]]; then echo "$index"; else echo "$DEFAULT"; fi)"
+  done
+  unset UNITS
+
+  read -p "Enter a number [0-"$(($(echo "$JSON" | jq length) - 1))"]: " INPUT
+  if ! [[ "$INPUT" =~ ^[0-9]+$ ]] || ! [[ "$INPUT" -ge "0" ]] || ! [[ "$INPUT" -le "$(($(echo "$JSON" | jq length) - 1))" ]]; then
+    echo "[ERROR] Input Not a Valid Number! Exiting."
+    exit 1
+  fi
+
+  if [[ "$INPUT" == "$DEFAULT" ]]; then
+    echo "[LOG] Selected Location is already Default"
+    echo "[LOG] Exiting"
+    exit 0
+  else
+    if [[ "$DEFAULT" == "" ]]; then
+      MOD="$(echo "$JSON" | jq ".[\"$INPUT\"].default = true")"
+      echo "$MOD" >"$SAVE_PATH"
+      echo "[LOG] Default Location Selected"
+    else
+      MOD="$(echo "$JSON" | jq ".[\"$INPUT\"].default = true" | jq ".[\"$DEFAULT\"].default = false")"
+      echo "$MOD" >"$SAVE_PATH"
+      echo "[LOG] Default Location Selected"
     fi
   fi
+  unset JSON
+  unset DEFAULT
 }
